### Register a new user
POST http://localhost:3000/users
Content-Type: application/json

{
  "first_name": "Lisa",
  "last_name": "Kudrow",
  "phone_number": "+54 022 395",
  "birthdate": "01-01-2002",
  "username": "lkudrow",
  "email": "lkudrow@test.com",
  "password": "123456"
}

### Log in a registered user
POST http://localhost:3000/login
Content-Type: application/json

{
  "username": "bcooper",
  "password": "123456"
}

### Retrieve logged-in user
GET http://localhost:3000/auto_login
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2fQ.dnjqXrQ8HWQnIiSMoM-Yt66LbXidwwtdvo2hcXoQBMU

### FIX: Create a new doctor
POST http://localhost:3000/api/v1/doctors
Content-Type: application/json
Authorization:

{}

### Get a list of all doctors
GET http://localhost:3000/api/v1/doctors
Accept: application/json

### Get a doctor by id
GET http://localhost:3000/api/v1/doctors/1
Accept: application/json

### FIX: Delete a doctor
DELETE http://localhost:3000/api/v1/doctors/2
Accept: application/json
Authorization:

### Get a list of all clinics
GET http://localhost:3000/api/v1/clinics
Accept: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2fQ.dnjqXrQ8HWQnIiSMoM-Yt66LbXidwwtdvo2hcXoQBMU

### Create an appointment
POST http://localhost:3000/api/v1/users/6/reservations
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2fQ.dnjqXrQ8HWQnIiSMoM-Yt66LbXidwwtdvo2hcXoQBMU

{
  "reservation_date": "28-08-2023",
  "reservation_time": "18:00",
  "status": true,
  "user": 6,
  "doctor_id": 2,
  "clinic_id": 7
}

### Get all appointments of a user
GET http://localhost:3000/api/v1/users/6/reservations
Accept: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjo2fQ.dnjqXrQ8HWQnIiSMoM-Yt66LbXidwwtdvo2hcXoQBMU
